spring:
  mvc:
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher,所以需要配置此参数
      matching-strategy: ANT_PATH_MATCHER
knife4j:
  enable: true
  #true则是生产环境不允许访问knife4j
  production: false
